### ISSUE TITLE
Advice for learning MCCs?

### ISSUE THREAD

**Issue by jnear** [AlexBravo/Twiddler#15]
This is not an issue with Backspice per se, but your advice was helpful to me before so I thought I would ask. I'm closing in on 30wpm with Backspice, practicing with keybr, but I haven't learned any of the MCCs and I'm not sure of the best way to go about doing this. I also want to learn all the punctuation marks, arrow keys, etc (my goal is to use the twiddler to run emacs). Do you have any advice for this stuff?

Thanks!

**Comment by AlexBravo** [comment]
Look for a cheat sheet and make flush cards. 
Then study these cards and try to visualize the chords when you type them.
Also you can print cheat sheet out and put it where you can see it.
I used to put it on the back of the Twiddler 2, and even Twiddler 3, even though Twiddler 3 is a little small.

If would be more beneficial to others if you ask questions like this one on Google+ and/or tekgear forum:
https://plus.google.com/u/0/collection/gA1nY
http://forum.tekgear.com/categories

**Comment by jnear** [comment]
Thanks - very helpful!
