### ISSUE TITLE
Simplified Backspice config does not match cheatsheet

### ISSUE THREAD

**Issue by xpucadad** [AlexBravo/Twiddler#16]
Alex,

I've been playing with my new Twiddler 3 and decided to switch from the full Backspice to the simplified one. I have found several discrepancies and was preparing to correct the config and the cheatsheet, but there are several cases for which it's not clear to me which is correct.

Here are some of the issues:
- MOOO is producing "I", not "s".
- Cheatsheet says v = i+t+a and y = i+h; however i+t+a is not producing anything and i+h is producing "v".  MOOL is producing "y", but is not shown on the cheatsheet.
- Cheatsheet shows "g" in 2 places, OMMO and MOOR, but MOOR is not producing anything.

I think I checked all the letters and numbers, but I didn't check the other characters as they seemed to match the full Backspice config, so I assumed you didn't make any changes when creating the simplified config from the original.

I wouldn't mind fixing the config or cheatsheet or both if you can clarify what your intent was. Probably the easiest thing would be for you to proof and correct the cheatsheet and then I can try to make the configuration agree with it.

I am using the original tuner as I'm not familiar with Twidor and am not sure it will work 100% correctly with the Twidler 3 layout. Do you think I should go ahead and learn how to use Twidor?

Thanks,

Ken

**Comment by AlexBravo** [comment]
You are right Ken, the latest set of changes involving moving of "s" to MOOO didn't make it into Simplified version. I use the full Backspice on Twiddler 3, so that is the "ground truth".

I fixed the issues you reported. Let me know if you find any other discrepancies.

I only used Twidor at the very beginning for a few months. I don't think it's worth learning it.

**Comment by xpucadad** [comment]
That was fast! I will sync and try it as soon as I can!

Thank you for the quick fix!
