### ISSUE TITLE
I tried importing the backspice 3 layout onto the tekgear tuner website, but it doesn't like the .cfg file

### ISSUE THREAD

**Issue by cmaughan** [AlexBravo/Twiddler#19]
Website complains that the layout is 'old' i.e. not version 4.
I also tried copying the .cfg file onto the twiddler; and it looks like the twiddler ignores it and goes to factory reset mode.

**Comment by AlexBravo** [comment]
That sure is unfortunate. Tuner and Configurator have been compatible for a long time...

**Comment by cmaughan** [comment]
What is configurator, how do I get it?

**Comment by cmaughan** [comment]
Turns out I wasn't downloading the 'RAW' version, and it was incompatible because of that; works OK now - though I'd still like to know how configurator works :)

**Comment by AlexBravo** [comment]
Configurator is an old program for making configurations. It's written in Java. 
You can find it in this repo. It's called "Configurator123 ...jar"
