### ISSUE TITLE
Tag last v1 commit

### ISSUE THREAD

**Issue by lancegatlin** [AlexBravo/Twiddler#22]
Hey Alex!

Can you please start using tags/releases? Noticed this morning the v in the cheat sheet no longer matched my config. I'm committed to v1 at this point so would be lovely to have a tag to pick that version. Release would also be great time to list all changes and why you did them.

Thanks!

-L

**Comment by AlexBravo** [comment]
Sorry for inconvenience Lance. 

I was thinking about doing different releases or branches and decided against it, as I myself am going to use and maintain only one version of the layout. The only reason I call it Backspice2 is the unprecedented number of changes that are coming. Please watch for a future post on Techgear Twiddler forum for explanation and justification of this major change. 

A short explanation of this change is this: the cognitive load of all MCCs is reduced to absolute minimum without loosing the benefits of MCCs. All MCCs now match the letters they represent. The only downside of this idea is the removal of "ion". Considering there's already "on", this downside is almost not noticeable though.
