### ISSUE TITLE
Google+ link in README is dead

### ISSUE THREAD

**Issue by bryanlarsen** [AlexBravo/Twiddler#25]
Was there anything interesting on that page?

**Comment by dansteen** [comment]
It was google+ - of course not!

**Comment by bryanlarsen** [comment]
Therefore the link should be deleted in the README and nothing will be lost.   I'm a newbie and was struggling, convinced that the broken link had everything I needed.   :)   But I got myself straightened out by reading the Twiddler documentation better.   No need to improve your docs, any suggestions I have should go to TekGear...

**Comment by AlexBravo** [comment]
This project is not being maintained anymore
